spring:
    profiles:
        active: prod
    resources.static-locations: classpath:/static
    data:
        rest:
            basePath: /api

    datasource:
        initialize: true
        data: classpath:/func.sql

server:
    port: 8082

h2:
    tcp:
        port: 9092
        enabled: true
    web:
        port: 8082
        enabled: true

logging:
    level:
        root: ERROR
        org.springframework.web: INFO
        org:
            hibernate: # DEBUG #for full debug log
                SQL: ERROR
                type: ERROR


log4j.logger.root: ERROR

app.backup.enabled: true
app.backup.interval: 30


