spring:
    profiles:
        active: test
    resources.static-locations: classpath:/static
    data:
        rest:
            basePath: /api

    datasource:
        initialize: true
        data: classpath:/data.sql

server:
    port: 8080

h2:
    tcp:
        port: 9092
        enabled: false
    web:
        port: 8082
        enabled: false

logging:
    file: app.log
    level:
        root: INFO
        org.springframework.web: INFO
        com.example.demo: DEBUG
        org:
            hibernate: # DEBUG #for full debug log
                SQL: DEBUG
                type: TRACE



