spring:
    profiles:
        active: test
    resources.static-locations: classpath:/static
    data:
        rest:
            basePath: /api

    datasource:
        initialize: true
        data: classpath:/data.sql

server:
    port: 8080