server:
  port: @server.port@

spring:
  profiles:
    active: @spring.profiles.active@
  mvc.static.pattern: /**
  resources.static-locations: classpath:/static
  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://localhost:3306/test_db
    username: root
    password: jAn22enin

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    database: MYSQL
    openInView: false
    show_sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
    properties:
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: true
      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory


  data:
    jpa.repositories.enabled: true